#!/usr/bin/env bash 
display_usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}
if [ $# -lt 4 ]; then
    display_usage
    exit 1
fi
file_to_transfer="$1"
server_ip="$2"
username="$3"
ssh_key="$4"
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_to_transfer" "$username@$server_ip:~/"
